### ISSUE TITLE
Wrong default mongodb port used

### ISSUE THREAD

**Issue by mlegenhausen** [techtraits/docker-uptime#2]
The default exposed port of mongodb is 27017 but you are using 28017. It would be nice if you could change this. So it plays better with the official mongo image from docker.

I will try to provide you a pull request.

**Comment by usmanismail** [comment]
I will clean this up. Another issue is that docket no longer recommends using end variables to lookup addresses. etc/hosts is updated to add links and those should be used

**Comment by mlegenhausen** [comment]
Ah nice hint thanks :)

**Comment by usmanismail** [comment]
I have setup Pull Request #3. I will not get the time to test it out until this weekend. Meanwhile if you have some free cycles I would love to get a second pair of eyes on it.
